name: ia4
channels:
  - conda-forge
dependencies:
  - click=8.3.1
  - matplotlib=3.10.8
  - numpy=2.3.5
  - pandas=2.3.3
  - python=3.11.14
  - quarto
  - yaml=0.2.5
  - pyyaml=6.0.3
  - conda-lock=3.0.4